name: CI

on:
  push:
    branches:
      - main

jobs:
  Windows:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Build Evie Launcher
        run: yarn && yarn build --win
      - name: Upload Release
        uses: actions/upload-artifact@master
        with:
          name: EvieLauncherReleaseWin
          path: "dist/Evie Client Setup 1.0.0.exe"
  MacOS:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Build Evie Launcher
        run: yarn && yarn build
      - name: Upload Release
        uses: actions/upload-artifact@master
        with:
          name: EvieLauncherReleaseMac
          path: "dist/Evie Client-1.0.0.dmg"
  Deploy:
    needs:
       - MacOS
       - Windows
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Git Sign-In
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions"
      - name: Get Mac Build
        uses: actions/download-artifact@master
        with:
          name: EvieLauncherReleaseMac
      - name: Get Windows Build
        uses: actions/download-artifact@master
        with:
          name: EvieLauncherReleaseWin
      - name: Publish
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            *.dmg
            *.exe