name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Build Evie Launcher
        run: yarn && yarn build --win
      - name: Upload Release
        uses: actions/upload-artifact@master
        with:
          name: EvieLauncherRelease
          path: "dist/Evie Client Setup 1.0.0.exe"
      - name: Push new version to master
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions"
      - name: Get Hub
        run: |
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          cd bin
          chmod +x hub
          cd ..
      - name: Get Release
        uses: actions/download-artifact@master
        with:
          name: EvieLauncherRelease
      - name: Publish
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_REPO_SECRET }}"
        run: |
          git clone https://github.com/EvieClient/EvieClient-Releases
          cd EvieClient-Releases
          ./../bin/hub release delete "latest-master"
          ./../bin/hub release create -a "../Evie Client Setup 1.0.0.exe" -m "Current Master Build: Evie Client Setup 1.0.0.exe" -p "latest-master"
